gestionOrphelinat/gestionBesoin/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("ajoutbesoin/", EnregistreBesoin, name = "ajoutbesoin"),  
    path("listebesoin/", ListeBesoin, name ="listebesoin"),
    path("consulterBesoin/<int:pk>", ConsulterBesoin, name = "consulterBesoin"),
    path("editerbesoin/<int:pk>" , editerBesoin, name = "editerbesoin"),
    path("modifierbesoin/<int:id_besoin>" , ModifierBesoin, name = "modifierbesoin"),
    path("suppressionbesoin/<int:id_besoin>" , SupprimerBesoin, name = "suppressionbesoin"),
    
]

gestionOrphelinat/gestionOrphelinat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from gestionUtilisateur.views import  logoutuser,home, Loginuser
from .views import *
app_name='gestionOrphelinat'
urlpatterns = [
    path('connexion', Loginuser, name='connexion'),
    path('deconnexion/', logoutuser, name='deconnexion'),
    path('accueil/', home, name='accueil'),
    path('logout/', RedirectView.as_view(url ='/admin/logout/')),
    path('admin/', admin.site.urls),
    path('About/', About, name="about"),
    path('services/', Services, name="services"),
    path('gallery/', Gallery, name="gallery"),
    path('contact/', Contact, name="contact"),
    path('', PageAccueil, name="pageaccueil"),
    path('Utilisateur/', include("gestionUtilisateur.urls")),
    path('Parrainage/', include("gestionParrainage.urls")),
    path('Finance/', include("gestionFinance.urls")),
    path('Besoin/', include("gestionBesoin.urls")),
    path('Activite/', include("gestionActivites.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionOrphelinat/gestionParrainage/urls.py
from django.urls import path
from .views import *
app_name= 'gestionParrainage'
urlpatterns = [
    path("ajoutCentre/<int:id_user>", EnregistreCentre, name = "ajoutCentre"), 
    path("ajoutEnfan/", EnregistreEnfant, name = "ajoutEnfant"), 
    path("ajoutDons/", EnregistreDons, name = "ajoutDons"), 
    path("ajoutParrain/<int:id_user>", EnregistreParrain, name = "ajoutParrain"),
    path("ajoutParrainer/", EnregistreParrainer, name = "ajoutParrainer"),
    path("listecentre/", ListeCentre, name = "listecentre"), 
    path("listeEnfant/", ListeEnfant, name = "listeEnfant"),
    path("listeDon/", ListeDon, name ="listeDon"), 
    path("listeparrain/", ListeParrain, name = "listeparrain"),
    path("listeParainer/", ListeParrainer, name = "listeParainer"),
    path("consulterCentre/<int:pk>", ConsulterCentre, name = "consulterCentre"), 
    path("consulterEnfant/<int:pk>", ConsulterEnfant, name = "consulterEnfant"), 
    path("consulterDon/<int:pk>", ConsulterDons, name = "consulterDon"), 
    path("consulterParrain/<int:pk>", ConsulterParrain, name = "consulterParrain"),
    path("consulterParrainer/<int:codes>", ConsulterParainer, name = "consulterParrainer"),
    path("editerCentre/<int:pk>", EditerCentre, name = "editerCentre"), 
    path("editerEnfant/<int:identifiant>", EditerEnfant, name = "editerEnfant"), 
    path("editerDon/<int:pk>", EditerDon, name = "editerDon"), 
    path("editerParrain/<int:kl>", EditerParrain, name = "editerParrain"), 
    path("editerParrainer/<int:codes>", editerParainer, name = "editerParrainer"), 
    path("supprimerParrainer/<int:codes>", SupprimerParainer, name = "supprimerParrainer"), 
    path("modificationCentre/<int:id_centre>", ModifierCentre, name = "modificationCentre"), 
    path("modificationEnfant/<int:identifiant>", ModificationEnfant, name = "modificationEnfant"), 
    path("modificationDon/<int:codes>", ModificationDon, name = "modificationDon"), 
    path("modificationParrain/<int:id_parrain>", ModifierParrain, name = "modificationParrain"), 
    path("modificationParrainer/<int:codes>", ModifierParrainer, name = "modificationParrainer"), 
    path("suppressionCentre/<int:id_centre>", SupprimerCentre, name = "suppressionCentre"), 
    path("supprimerEnfant/<int:identifiant>", SupprimerEnfant, name = "supprimerEnfant"), 
    path("supprimerDon/<int:pk>", SupprimerDons, name = "supprimerDon"), 
    path("suppressionParrain/<int:id_parrain>", SupprimerParrain, name = "suppressionParrain"), 
    path("filtrerEnfant/", RechercherEnfant, name = "filtrerEnfant"), 
    path("rechercherDon/", RechercherDon, name = "rechercherDon"), 
    path("rechercherCentre", RechercherCentre, name = "rechercherCentre"), 
    path("rechercherParrain", RechercherParrain, name = "rechercherParrain"), 
    
]

gestionOrphelinat/gestionParrainage/models.py
from django.db import models
from gestionUtilisateur.models import Utilisateur
# Create your models here.
SEXE = (('Sélectionner', 'Sélectionner un sexe'),('Masculin', 'Masculin'), ('Feminin', 'Feminin'))
STATUT_ENFANT = (('Sélectionner', 'Sélectionner un statut'),('Orphelin de Père', 'Orphelin de Père'), ('Orphelin de Mère', 'Orphelin de Mère'), ('Adopté', 'Adopté'), ('Orphelin Père/Mère', 'Orphelin Père/Mère'))

#====================================Centre Orphelinat=====================================
class Centre_Orphelinat(models.Model):
    raison_sociale = models.CharField(max_length=100)
    contact1 = models.CharField(max_length=25)
    contact2 = models.CharField(max_length=25, blank=True)
    email = models.EmailField()
    localisation = models.CharField(max_length=100)
    logo = models.ImageField(upload_to='media/Centres', blank=True)
    responsable = models.CharField(max_length=55, blank=True)
    date_creation = models.DateField()
    capacite = models.IntegerField()
    id_utilisateur = models.OneToOneField(Utilisateur, on_delete = models.CASCADE)
    
    @property
    def utilisateur(self):
        return '{}'.format(self.id_utilisateur)
    def __str__(self):
     return '{} {} {}'.format(self.raison_sociale, self.contact1, self.email)

#=======================================Parrain======================================
class Parrain(models.Model):
    nom_par = models.CharField(max_length=60)
    adresse_par = models.CharField(max_length=55)
    contact_par = models.CharField(max_length=35)
    email_par = models.EmailField()
    id_utilisateur = models.OneToOneField(Utilisateur, on_delete = models.CASCADE)
    
    @property
    def utilisateur(self):
        return '{}'.format(self.id_utilisateur)
    def __str__(self):
        return '{} {} {}'.format(self.nom_par, self.contact_par, self.email_par)
#==============================Orphelin====================================================
class Enfant(models.Model):
    nom_enf = models.CharField(max_length=65)
    prenom_enf = models.CharField(max_length= 65)
    date_admission = models.DateField()
    sexe_enf = models.CharField(max_length=35, choices = SEXE, default = "Sélectionner")
    statut_enf = models.CharField(max_length = 250, choices = STATUT_ENFANT, default = "Sélectionner")
    photo_enf = models.FileField(upload_to ='media/Enfants', blank= True)
    date_naissance = models.DateField()
    profession_enf = models.CharField(max_length = 100)
    lieu_naissance = models.CharField(max_length = 65)
    pere_enf = models.CharField(max_length = 64)    
    mere_enf = models.CharField(max_length = 60)  
    id_centre = models.ForeignKey(Centre_Orphelinat,on_delete = models.CASCADE)
    
    def __str__(self):
        return '{} {} {} {} {}'.format(self.nom_enf, self.prenom_enf, self.statut_enf, self.pere_enf, self.mere_enf)  
    
    @property
    def centre(self):
        return '{}'.format(self.id_centre)
#================================Dons====================================================
class Dons(models.Model):
    type_dons = models.CharField(max_length = 10)
    date_don = models.DateField(auto_now = True)
    description_don = models.CharField(max_length = 100)
    montant_don = models.DecimalField(max_digits=12, decimal_places = 2)
    id_centre = models.ForeignKey(Centre_Orphelinat, on_delete= models.CASCADE)
    id_parrain = models.ForeignKey(Parrain,on_delete= models.CASCADE)
    
    def __str__(self):
        return '{}{}{}'.format(self.type_don, self.description_don, self.montant_don)
    
    @property
    def parrain(self):
        return '{}'.format(self.id_parrain)
    
    @property
    def centre(self):
        return '{}'.format(self.id_centre)
#===============================Parrainage=================================================
class Parrainage(models.Model):
    id_enfant = models.ForeignKey(Enfant, on_delete= models.CASCADE)
    id_parrain = models.ForeignKey(Parrain,on_delete= models.CASCADE)
    date_parrainage = models.DateField(auto_now= True)
    
    def __str__(self):
        return '{}{}{}'.format(self.id_enfant, self.id_parrain, self.date_parrainage)
    
    
    @property
    def enfant(self):
        return '{}'.format(self.id_enfant)
    
    @property
    def parrain(self):
        return '{}'.format(self.id_parrain)
#===============================================================================

gestionOrphelinat/gestionParrainage/templates/gestionParrainage/ajoutEnfant.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block titre_page %} GESTION DES ENFANTS ORPHELIN {% endblock  %}

{% block titre_cadre %} ENREGISTRER UN ORPHELIN {% endblock titre_cadre %}

{% block formulaire %}

<form action = "" method="POST" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{form.nom_enf | as_crispy_field}}
        </div>		
    </div>
    
    <div class="col-md-6">
        <div class="form-group">
            {{form.prenom_enf | as_crispy_field}}
        </div>		
    </div>

   </div>

   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{form.date_admission | as_crispy_field}}
        </div>		
    </div>
    
    <div class="col-md-6">
        <div class="form-group">
            {{form.sexe_enf | as_crispy_field}}
        </div>		
    </div>

   </div>

   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{form.statut_enf | as_crispy_field}}
        </div>		
    </div>
    
    <div class="col-md-6">
        <div class="form-group">
            {{form.photo_enf | as_crispy_field}}
        </div>		
    </div>

   </div>

   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{form.date_naissance | as_crispy_field}}
        </div>		
    </div>
    
    <div class="col-md-6">
        <div class="form-group">
            {{form.profession_enf | as_crispy_field}}
        </div>		
    </div>

   </div>

   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{form.lieu_naissance | as_crispy_field}}
        </div>		
    </div>
    
    <div class="col-md-6">
        <div class="form-group">
            {{form.pere_enf | as_crispy_field}}
        </div>		
    </div>

   </div>

   <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {{form.mere_enf | as_crispy_field}}
        </div>		
    </div>
    
    <div class="col-md-6">
        <div class="form-group">
            {{form.id_centre | as_crispy_field}}
        </div>		
    </div>

   </div>

    <div class="form-group">
        <div class="text-center">
            <button type="submit" class="btn btn-success bt-sm">Enregistrer &nbsp;<i class="fa-solid fa-save"></i></button>
            <button type="reset" class="btn btn-warning bt-sm">Annuler &nbsp;<i class="fa-solid fa-refresh"></i></button>
            <a href="{% url 'listeEnfant' %}" class="btn btn-info bt-sm">Voir Liste &nbsp;<i class="fa-solid fa-arrow-right"></i></a>
        </div>
    </div>
    
</form>


{% endblock %}

gestionOrphelinat/gestionParrainage/templates/gestionParrainage/ajoutParainer.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block titre_page %} GESTION DE PARAINAGE {% endblock  %}

{% block titre_cadre %} ENREGISTRER UN PARRAINAGE {% endblock titre_cadre %}

{% block formulaire %}

<form action = "" method="POST" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        {{form|crispy}}
    </div>
    <div class="form-group">
        <div class="text-center">
            <button type="submit" class="btn btn-success bt-sm">Enregistrer &nbsp;<i class="fa-solid fa-save"></i></button>
            <button type="reset" class="btn btn-warning bt-sm">Annuler &nbsp;<i class="fa-solid fa-refresh"></i></button>
            <a href="{% url 'listeParainer' %}" class="btn btn-info bt-sm">Voir Liste &nbsp;<i class="fa-solid fa-arrow-right"></i></a>
        </div>
    </div>
    
</form>


{% endblock %}

gestionOrphelinat/gestionParrainage/templates/gestionParrainage/ajoutParrain.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block titre_page %} GESTION DES PARRAINS {% endblock  %}

{% block titre_cadre %} ENREGISTREMENT D'UN PARRAIN {% endblock titre_cadre %}

{% block formulaire %}

<form action = "" method="POST" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {{form|crispy}}
    </div>
    <div class="form-group">
        <div class="text-center">
            <button type="submit" class="btn btn-success bt-sm">Enregistrer &nbsp;<i class="fa-solid fa-save"></i></button>
            <button type="reset" class="btn btn-warning bt-sm">Annuler &nbsp;<i class="fa-solid fa-refresh"></i></button>
               
        </div>
    </div>
    
</form>


{% endblock %}

gestionOrphelinat/gestionParrainage/templates/gestionParrainage/consulterCentre.html
{% extends 'base.html' %}
{% block titre_page %} AFFICHAGE DES CENTRES {% endblock %}

{% block titre_cadre %}
AFFICHER UN CENTRE
{% endblock %}

{% block formulaire %}

<form action="" method="GET" class="form-horizontal">

	{% csrf_token %}

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="id_centre">ID du Centre</label>
				<input type="text" id="id_centre" class="form-control" name="id_centre" value="{{infoCentre.id}}" readonly title="Identifiant du Centre">
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="nom_centre">Raison Sociale</label>
				<input type="text" id="nom_centre" class="form-control" name="nom_centre" value="{{infoCentre.raison_sociale}}" readonly title="Le nom du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="contact1">Contact 1</label>
				<input type="text" id="contact1" class="form-control" name="contact1" value="{{infoCentre.contact1}}" readonly title="Le contact1 du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="contact2">Contact 2</label>
				<input type="text" id="contact2" class="form-control" name="contact2" value="{{infoCentre.contact2}}" readonly title="Le contact 2 du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="email">E-mail du Centre</label>
				<input type="text" id="email" class="form-control" name="email" value="{{infoCentre.email}}" readonly title="E-mail du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="localisation">Localisation du Centre </label>
				<input type="text" id="localisation" class="form-control" name="localisation" value="{{infoCentre.localisation}}" readonly title="La localisation du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="responsable">Responsable du Centre</label>
				<input type="text" id="responsable" class="form-control" name="responsable" value="{{infoCentre.responsable}}" readonly title="Responsable du Centre">
			</div>		
		</div>	
	</div>
    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="date_creation">Date de création</label>
				<input type="text" id="date_creation" class="form-control" name="date_creation" value="{{infoCentre.date_creation}}" readonly title="La date de création">
			</div>		
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="capacite">Capacité d'accueil</label>
				<input type="text" id="capacite" class="form-control" name="capacite" value="{{infoCentre.capacite}}" readonly title="la capacité d'accueil">
			</div>		
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<a href="{% url 'listecentre' %}" class="btn btn-secondary btn-lg" title="Page précédente" target="_self">Retour &nbsp; <i class="fa fa-arrow-left"></i></a>
			</div>		
		</div>	
	</div>
</form>

{% endblock %}

gestionOrphelinat/gestionParrainage/templates/gestionParrainage/consulterDons.html
{% extends 'base.html' %}
{% block titre_page %} GESTION DES DONS {% endblock %}

{% block titre_cadre %}
AFFICHER UN DON
{% endblock %}

{% block formulaire %}

<form action="" method="GET" class="form-horizontal">

	{% csrf_token %}

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="id_don">ID du Don</label>
				<input type="text" id="id_don" class="form-control" name="id_don" value="{{infoDon.id}}" readonly title="Identifiant du Don">
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="type_dons">Le type de Don</label>
				<input type="text" id="type_dons" class="form-control" name="type_dons" value="{{infoDon.type_dons}}" readonly title="Le type du Don">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="date_don">Date du Don</label>
				<input type="text" id="date_don" class="form-control" name="date_don" value="{{infoDon.date_don}}" readonly title="La date du Don">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="description_don">Description du Don</label>
				<input type="text" id="description_don" class="form-control" name="description_don" value="{{infoDon.description_don}}" readonly title="La description du don">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="montant_don">Montant du Don</label>
				<input type="text" id="montant_don" class="form-control" name="montant_don" value="{{infoDon.montant_don}}" readonly title="Le montant du Don">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="id_centre">Centre </label>
				<input type="text" id="id_centre" class="form-control" name="id_centre" value="{{infoDon.id_centre.raison_sociale}}" readonly title="Centre">
			</div>		
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="id_parrain">Parrain </label>
				<input type="text" id="id_parrain" class="form-control" name="id_parrain" value="{{infoDon.id_parrain.nom_par}}" readonly title="Centre">
			</div>		
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<a href="{% url 'listeDon' %}" class="btn btn-secondary btn-lg" title="Page précédente" target="_self">Retour &nbsp; <i class="fa fa-arrow-left"></i></a>
			</div>		
		</div>	
	</div>
</form>

{% endblock %}

gestionOrphelinat/gestionParrainage/templates/gestionParrainage/consulterParrain.html
{% extends 'base.html' %}
{% block titre_page %} AFFICHAGE DES PARRAINS {% endblock %}

{% block titre_cadre %}
AFFICHER UN PARRAIN
{% endblock %}

{% block formulaire %}

<form action="" method="GET" class="form-horizontal">

	{% csrf_token %}

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="id_parrain">ID du Parrain</label>
				<input type="text" id="id_parrain" class="form-control" name="id_parrain" value="{{infoParrain.id}}" readonly title="Identifiant du parrain">
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="nom_par"> Nom et Prénom</label>
				<input type="text" id="nom_par" class="form-control" name="nom_par" value="{{infoParrain.nom_par}}" readonly title="Le nom complet du Parrain">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="adresse_par">Adresse </label>
				<input type="text" id="adresse_par" class="form-control" name="adresse_par" value="{{infoParrain.adresse_par}}" readonly title="L'adresse du Parrain">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="contact_par">Contact </label>
				<input type="text" id="contact_par" class="form-control" name="contact_par" value="{{infoParrain.contact_par}}" readonly title="Le contact du Parrain">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="email_par">E-mail du Centre</label>
				<input type="text" id="email_par" class="form-control" name="email_par" value="{{infoParrain.email_par}}" readonly title="E-mail du Parrain">
			</div>		
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<a href="{% url 'listeparrain' %}" class="btn btn-secondary btn-lg" title="Page précédente" target="_self">Retour &nbsp; <i class="fa fa-arrow-left"></i></a>
			</div>		
		</div>	
	</div>
</form>

{% endblock %}

gestionOrphelinat/gestionParrainage/templates/gestionParrainage/modifierCentre.html
{% extends 'base.html' %}
{% block titre_page %} EDITION DES CENTRES {% endblock %}

{% block titre_cadre %}
MODIFICATION D'UN CENTRE
{% endblock %}

{% block formulaire %}

<form action="{% url 'modificationCentre'  infoCentre.id %}" method="POST" class="form-horizontal" enctype="multipart/form-data">

	{% csrf_token %}

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="id_centre">ID du Centre</label>
				<input type="text" id="id_centre" class="form-control" name="id_centre" value="{{infoCentre.id}}" readonly title="Identifiant du Centre">
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				{% if infoCentre.logo %}
				<a href="{{infoCentre.logo.url}}" target="_blank" title="Logo du centre"><img src="{{infoCentre.logo.url}}" width ="20%", height="20%"></a>	
				{% else %}
				<label for="id_centre">Logo Indisponible</label>
				{% endif %}
				<input type="file" id="id_logo" class="form-control" name="logo" title="Importer le logo">
				
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="nom_centre">Raison Sociale</label>
				<input type="text" id="nom_centre" class="form-control" name="nom_centre" value="{{infoCentre.raison_sociale}}" title="Le nom du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="contact1">Contact 1</label>
				<input type="text" id="contact1" class="form-control" name="contact1" value="{{infoCentre.contact1}}" title="Le contact1 du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="contact2">Contact 2</label>
				<input type="text" id="contact2" class="form-control" name="contact2" value="{{infoCentre.contact2}}" title="Le contact 2 du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="email">E-mail du Centre</label>
				<input type="text" id="email" class="form-control" name="email" value="{{infoCentre.email}}" title="E-mail du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="localisation">Localisation du Centre </label>
				<input type="text" id="localisation" class="form-control" name="localisation" value="{{infoCentre.localisation}}" title="La localisation du Centre">
			</div>		
		</div>	
	</div>

    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="responsable">Responsable du Centre</label>
				<input type="text" id="responsable" class="form-control" name="responsable" value="{{infoCentre.responsable}}" title="Responsable du Centre">
			</div>		
		</div>	
	</div>
    <div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="date_creation">Date de création</label>
				<input type="text" id="date_creation" class="form-control" name="date_creation" value="{{infoCentre.date_creation |date:'Y-n-j'}}" title="La date de création">
			</div>		
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<label for="capacite">Capacité d'accueil</label>
				<input type="text" id="capacite" class="form-control" name="capacite" value="{{infoCentre.capacite}}" title="la capacité d'accueil">
			</div>		
		</div>	
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<button type="submit" class="btn btn-info bt-sm">Modifier &nbsp;<i class="fa-solid fa-edit"></i></button>
				<a href="{% url 'listecentre' %}" class="btn btn-secondary btn-lg" title="Page précédente" target="_self">Retour &nbsp; <i class="fa fa-arrow-left"></i></a>
			</div>		
		</div>	

	</div>
</form>

{% endblock %}